version: "3.8"

services:
  weibo-sentiment-tensorflow:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    image: weibo-sentiment-analysis:gpu-latest
    container_name: weibo-sentiment-tensorflow
    volumes:
      - ./:/workspace
      - ./data:/workspace/data
      - ./logs:/workspace/logs
    working_dir: /workspace
    environment:
      - PYTHONUNBUFFERED=1
      - TF_CPP_MIN_LOG_LEVEL=1 # 减少TensorFlow日志输出
      - CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 # 使用所有8张GPU
      - NVIDIA_VISIBLE_DEVICES=all # 确保所有GPU可见
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: python src/main.py
    tty: true
    stdin_open: true
    networks:
      - default

networks:
  default:
    driver: bridge
